export const FETCH_ORGANIZER_REGISTRY_CONTENT_START = 'FETCH_ORGANIZER_REGISTRY_CONTENT_START';
export const FETCH_ORGANIZER_REGISTRY_CONTENT_SUCCESS = 'FETCH_ORGANIZER_REGISTRY_CONTENT_SUCCESS';
export const FETCH_ORGANIZER_REGISTRY_CONTENT_FAIL = 'FETCH_ORGANIZER_REGISTRY_CONTENT_FAIL';

export const SEARCH_ORGANIZATION_BY_NAME_START = 'SEARCH_ORGANIZATION_BY_NAME_START';
export const SEARCH_ORGANIZATION_BY_NAME_SUCCESS = 'SEARCH_ORGANIZATION_BY_NAME_SUCCESS';
export const SEARCH_ORGANIZATION_BY_NAME_FAIL = 'SEARCH_ORGANIZATION_BY_NAME_FAIL';

// TODO: Delete below
export const FETCH_ORGANIZERS_START = 'FETCH_ORGANIZERS_START';
export const FETCH_ORGANIZERS_SUCCESS = 'FETCH_ORGANIZERS_SUCCESS';
export const FETCH_ORGANIZERS_FAIL = 'FETCH_ORGANIZERS_FAIL';

export const FETCH_ORGANIZATIONS_START = 'FETCH_ORGANIZATIONS_START';
export const FETCH_ORGANIZATIONS_SUCCESS = 'FETCH_ORGANIZATIONS_SUCCESS';
export const FETCH_ORGANIZATIONS_FAIL = 'FETCH_ORGANIZATIONS_FAIL';

// old
export const LOAD_ORGANIZERS_PENDING = 'LOAD_ORGANIZERS_PENDING';
export const LOAD_ORGANIZERS_SUCCESS = 'LOAD_ORGANIZERS_SUCCESS';
export const LOAD_ORGANIZERS_ERROR = 'LOAD_ORGANIZERS_ERROR';

export const LOAD_ORGANIZATIONS_BY_OIDS_PENDING = 'LOAD_ORGANIZATIONS_BY_OIDS_PENDING';
export const LOAD_ORGANIZATIONS_BY_OIDS_SUCCESS = 'LOAD_ORGANIZATIONS_BY_OIDS_SUCCESS';

export const LOAD_ORGANIZATIONS_BY_FREE_TEXT_PENDING = 'LOAD_ORGANIZATIONS_BY_FREE_TEXT_PENDING';
export const LOAD_ORGANIZATIONS_BY_FREE_TEXT_SUCCESS = 'LOAD_ORGANIZATIONS_BY_FREE_TEXT_SUCCESS';

export const CREATE_ORGANIZER_SUCCESS = 'CREATE_ORGANIZER_SUCCESS';
export const CREATE_ORGANIZER_RESET = 'CREATE_ORGANIZER_RESET';
