export const FETCH_ORGANIZER_REGISTRY_CONTENT_START =
  'FETCH_ORGANIZER_REGISTRY_CONTENT_START';
export const FETCH_ORGANIZER_REGISTRY_CONTENT_SUCCESS =
  'FETCH_ORGANIZER_REGISTRY_CONTENT_SUCCESS';
export const FETCH_ORGANIZER_REGISTRY_CONTENT_FAIL =
  'FETCH_ORGANIZER_REGISTRY_CONTENT_FAIL';
