export const FETCH_REGISTRY_CONTENT_START = 'FETCH_REGISTRY_CONTENT_START';
export const FETCH_REGISTRY_CONTENT_SUCCESS = 'FETCH_REGISTRY_CONTENT_SUCCESS';
export const FETCH_REGISTRY_CONTENT_FAIL = 'FETCH_REGISTRY_CONTENT_FAIL';

export const FETCH_ORGANIZATIONS_START = 'FETCH_ORGANIZATIONS_START';
export const FETCH_ORGANIZATIONS_SUCCESS = 'FETCH_ORGANIZATIONS_SUCCESS';
export const FETCH_ORGANIZATIONS_FAIL = 'FETCH_ORGANIZATIONS_FAIL';

export const ADD_REGISTRY_ITEM_START = 'ADD_REGISTRY_ITEM_START';
export const ADD_REGISTRY_ITEM_SUCCESS = 'ADD_REGISTRY_ITEM_SUCCESS';
export const ADD_REGISTRY_ITEM_FAIL = 'ADD_REGISTRY_ITEM_FAIL';

export const UPDATE_REGISTRY_ITEM_START = 'UPDATE_REGISTRY_ITEM_START';
export const UPDATE_REGISTRY_ITEM_SUCCESS = 'UPDATE_REGISTRY_ITEM_SUCCESS';
export const UPDATE_REGISTRY_ITEM_FAIL = 'UPDATE_REGISTRY_ITEM_FAIL';

export const DELETE_REGISTRY_ITEM_START = 'DELETE_REGISTRY_ITEM_START';
export const DELETE_REGISTRY_ITEM_SUCCESS = 'DELETE_REGISTRY_ITEM_SUCCESS';
export const DELETE_REGISTRY_ITEM_FAIL = 'DELETE_REGISTRY_ITEM_FAIL';

export const FETCH_EXAM_SESSION_CONTENT_START = 'FETCH_EXAM_SESSION_CONTENT_START';
export const FETCH_EXAM_SESSION_CONTENT_SUCCESS = 'FETCH_EXAM_SESSION_CONTENT_SUCCESS';
export const FETCH_EXAM_SESSION_CONTENT_FAIL = 'FETCH_EXAM_SESSION_CONTENT_FAIL';

export const EXAM_SESSION_FAIL_RESET = 'EXAM_SESSION_FAIL_RESET';
export const REGISTRY_FAIL_RESET = 'REGISTRY_FAIL_RESET';

export const ADD_EXAM_SESSION_START = 'ADD_EXAM_SESSION_START';
export const ADD_EXAM_SESSION_SUCCESS = 'ADD_EXAM_SESSION_SUCCESS';
export const ADD_EXAM_SESSION_FAIL = 'ADD_EXAM_SESSION_FAIL';

export const FETCH_EXAM_SESSION_PARTICIPANTS_START = 'FETCH_EXAM_SESSION_PARTICIPANTS_START';
export const FETCH_EXAM_SESSION_PARTICIPANTS_SUCCESS = 'FETCH_EXAM_SESSION_PARTICIPANTS_SUCCESS';
export const FETCH_EXAM_SESSION_PARTICIPANTS_FAIL = 'FETCH_EXAM_SESSION_PARTICIPANTS_FAIL';

export const UPDATE_EXAM_SESSION_START = 'UPDATE_EXAM_SESSION_START';
export const UPDATE_EXAM_SESSION_SUCCESS = 'UPDATE_EXAM_SESSION_SUCCESS';
export const UPDATE_EXAM_SESSION_FAIL = 'UPDATE_EXAM_SESSION_FAIL';

export const DELETE_EXAM_SESSION_START = 'DELETE_EXAM_SESSION_START';
export const DELETE_EXAM_SESSION_SUCCESS = 'DELETE_EXAM_SESSION_SUCCESS';
export const DELETE_EXAM_SESSION_FAIL = 'DELETE_EXAM_SESSION_FAIL';

export const CANCEL_REGISTRATION_START = 'CANCEL_REGISTRATION_START';
export const CANCEL_REGISTRATION_SUCCESS = 'CANCEL_REGISTRATION_SUCCESS';
export const CANCEL_REGISTRATION_FAIL = 'CANCEL_REGISTRATION_FAIL';
