export const FETCH_ORGANIZER_REGISTRY_CONTENT_START =
  'FETCH_ORGANIZER_REGISTRY_CONTENT_START';
export const FETCH_ORGANIZER_REGISTRY_CONTENT_SUCCESS =
  'FETCH_ORGANIZER_REGISTRY_CONTENT_SUCCESS';
export const FETCH_ORGANIZER_REGISTRY_CONTENT_FAIL =
  'FETCH_ORGANIZER_REGISTRY_CONTENT_FAIL';
export const FETCH_ORGANIZATIONS_START = 'FETCH_ORGANIZATIONS_START';
export const FETCH_ORGANIZATIONS_SUCCESS = 'FETCH_ORGANIZATIONS_SUCCESS';
export const FETCH_ORGANIZATIONS_FAIL = 'FETCH_ORGANIZATIONS_FAIL';
