export const FETCH_REGISTRY_CONTENT_START = 'FETCH_REGISTRY_CONTENT_START';
export const FETCH_REGISTRY_CONTENT_SUCCESS = 'FETCH_REGISTRY_CONTENT_SUCCESS';
export const FETCH_REGISTRY_CONTENT_FAIL = 'FETCH_REGISTRY_CONTENT_FAIL';

export const FETCH_ORGANIZATIONS_START = 'FETCH_ORGANIZATIONS_START';
export const FETCH_ORGANIZATIONS_SUCCESS = 'FETCH_ORGANIZATIONS_SUCCESS';
export const FETCH_ORGANIZATIONS_FAIL = 'FETCH_ORGANIZATIONS_FAIL';

export const ADD_REGISTRY_ITEM_START = 'ADD_REGISTRY_ITEM_START';
export const ADD_REGISTRY_ITEM_SUCCESS = 'ADD_REGISTRY_ITEM_SUCCESS';
export const ADD_REGISTRY_ITEM_FAIL = 'ADD_REGISTRY_ITEM_FAIL';
